builds:
  am:
    composite: 1121121 # FotM_Mis_AS_MB_AM
    single: 1111121 # FotM_ToF_AS_MB_AM
  hv:
    composite: 1121122 # FotM_Mis_AS_MB_HV
    single: 1111122 # FotM_ToF_AS_MB_HV
covenants:
  - kyrian
  - night_fae
  - venthyr
  - necrolord
sims:
  apl:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - shadowflametest.simc
  conduits:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  consumables:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  covenant-choice:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - CovenantRange
    files:
      - choice.simc
  covenants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  enchants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  gear:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  legendaries:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - legendaries.simc
  racials:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  soulbinds-launch:
    soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  stats:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - AM_sf.simc
      - AM_ecctv.simc
  trinkets:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: item
    steps:
      - 155
      - 158
      - 165
      - 170
      - 175
      - 183
      - 187
      - 190
      - 194
      - 195
      - 197
      - 200
      - 203
      - 204
      - 207
      - 210
      - 213
      - 216
      - 220
      - 223
      - 226
      - 233
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    builds: true
    weights: true
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
simcBuild: local
localBuild: ./simc.exe
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 2
  retryInterval: 20
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 400
  steps: 100
  total: 1400
  include:
    - mastery
    - haste
    - crit
    - versatility
